#!/bin/bash
set -e
BLK_TARGET=/mnt/d/bitcoin-data/blocks #Replace with your destination, no trailing slash

cd ~/.bitcoin/blocks
find . -name '*.dat' -type f -printf '%f\n' > tomove
while read line; do
        echo $line
        mv "$line" "$BLK_TARGET/$line"
        ln -s "$BLK_TARGET/$line" "$line"
done <tomove
rm tomove
echo Done
cd - 